### ISSUE TITLE
Hamburger menu doesn't always show

### ISSUE THREAD

**Issue by tech189** [claudebarde/akkadian-conjugator#1]
Great website! But I have encountered a bug:

The hamburger menu doesn't appear at every window width, in between full width and mobile width, when you press the menu button the screen dims but no menu appears. You can also see the verb dropdown menu overflow the sidebar at this size. I can reproduce it in both Firefox and Chrome.
<img width="946" alt="Screenshot 2020-02-01 at 10 12 05" src="https://user-images.githubusercontent.com/10728085/73590627-8dc1be80-44dc-11ea-962b-d01badfda309.png">
Maybe this is because the verb list is already visible?

**Comment by claudebarde** [comment]
Hi! Thank you for reporting the bug.
After having a quick look, it seems that there are some issues with the classes I added from Bulma. I will try to resolve it as soon as possible!

**Comment by claudebarde** [comment]
I published a corrected version of the website, please let me know if the bug is still present.
Thanks!

**Comment by tech189** [comment]
That's fixed it! Minor issue is that the contact form and Github repo links are missing from the top of the sidebar when the window is at this width (they appear again when you shrink the window):
<img width="282" alt="image" src="https://user-images.githubusercontent.com/10728085/73593449-6a0e7080-44fc-11ea-8882-5e97f379ad87.png">

**Comment by claudebarde** [comment]
The contact form and Github repo links don't appear in the left sidebar for the mobile view because they appear in the navbar instead (as there is more space to display them). It would otherwise be redundant.
![image](https://user-images.githubusercontent.com/25201109/73595032-86baa080-451c-11ea-8f53-30fc0ae32721.png)

**Comment by tech189** [comment]
Yes they move into the navbar at the maximum width, but if you shrink the window a bit they appear neither in the navbar nor in the sidebar:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/10728085/73595640-e1e79580-4512-11ea-8fbb-ab554c019ea6.png">

**Comment by claudebarde** [comment]
You are right, I modified the Bulma classes.
Thank you very much for your help!!

**Comment by tech189** [comment]
Looks good now, no problem!
